language: scala
sudo: required
dist: trusty

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC1
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

install: /bin/true

script:
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis-jvmopts clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
